Feature/rest api 3
KU-LeumBridge/KULEUM_BRIDGE_IOS pull request #13
Opened 2023-07-23 07:52 UTC by choiseoo

## 📚 개요

> 맛집 데이터 생성 : API를 통해 맛집 json 데이터를 Store 구조체로 받아왔습니다.
>카테고리별 데이터 리스트 연결 : 받아온 데이터를 통해 각각의 카테고리별로 데이터가 분류되게 했습니다.
>리스트 클릭 시 상세정보뷰로 연결 :리스트를 클릭하면 해당 맛집의 상세 정보 뷰로 넘어가게 했습니다.

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

> 카테고리별 데이터 리스트 구현
(TastePlaceView에서 카테고리 클릭 시 확인 가능합니다.)
<img width="200" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/102604192/3f6d6803-ce08-4c97-a175-9f0fb900650f">
<img width="200" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/102604192/26c02a8e-50be-4298-8558-33a06ce85b77">
<img width="200" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/102604192/0f7043a6-2d1a-4146-8252-749d9be1f596">

>리스트 클릭 시 상세정보 뷰와 데이터 연결
<img width="200" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/102604192/f297cd8e-eeea-47ea-a43f-db7dc6fabca7">
<img width="200" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/102604192/66f7677c-fa9f-4397-9561-73c8b739ce23">

2023-07-24 13:21 UTC, Ji-InPark requested changes

2023-07-24 13:21 UTC, Ji-InPark commented on KuleumBridge/Model/TasteAPI.swift
> +    }
여기 코드 전체적으로 설명 한 번 해주세요

2023-07-24 13:21 UTC, Ji-InPark commented on KuleumBridge/TastePlace/FoodListView.swift
> +    }
isEqualToCategory 메소드가 꼭 필요한 건가요??
네이밍도 조금.. 애매하네요...

store의 category를 string이 아닌 Category 타입으로 넣으면 이렇게 메소드를 따로 사용하지 않고 편하게 비교가 가능하겠죠?

2023-07-24 13:21 UTC, Ji-InPark commented on KuleumBridge/TastePlace/FoodStoreInfoData.swift
> +                Text(store.storeName)
이미지가 사라졌군요?? 
이제는 사용하지 않는건가요?

2023-07-24 13:21 UTC, Ji-InPark commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: "술집", foodImage: "soju")
이렇게 raw String을 사용하는 것은 매우 안좋은 개발 방법입니다.
enum을 만들었다면 enum을 최대한 활용해주세요.

https://stackoverflow.com/questions/24701075/swift-convert-enum-value-to-string
여기 참고해서 enum의 toString을 사용하듯이 만들어주세요.
그렇다면 categoryName을 굳이 넘겨줄 필요가 없게 되겠죠?
그렇다면 쭉 트리처럼 연결되어있던 파라매터들을 전부 없앨 수 있어 코드도 더 간결해질거구요

2023-07-24 13:35 UTC, choiseoo commented on KuleumBridge/TastePlace/FoodStoreInfoData.swift
> +                Text(store.storeName)
음 .. 네 일단 없애놓긴 했는데 추후에 넣어도 될 것 같기도 하구요..?

2023-07-24 13:36 UTC, choiseoo commented on KuleumBridge/TastePlace/FoodListView.swift
> +    }
Category타입으로 받으려고 했는데 json 데이터가 String으로 들어와서 함수 따로 설정 해둔 것 입니다.

2023-07-24 13:37 UTC, choiseoo commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: "술집", foodImage: "soju")
오 네 수정하겠습니당~

2023-07-24 13:38 UTC, Ji-InPark commented on KuleumBridge/TastePlace/FoodListView.swift
> +    }
그럼 파싱해서 넣으면 되겠죠?

2023-07-24 13:39 UTC, Guryss commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: "술집", foodImage: "soju")
raw string이 catogoryName값들 말하는거 맞죠?

2023-07-24 13:40 UTC, Ji-InPark commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: "술집", foodImage: "soju")
넵 맞습니다. 저렇게 String 필요할 때 직접 만들어서 사용하는걸 raw string이라고 해요
보통 그런걸 enum화나 resource화 시켜서 typo 에러를 막죠

2023-07-24 13:51 UTC, choiseoo commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: "술집", foodImage: "soju")
음 아 근데 저렇게 해놓은게.. json에 들어간 카테고리값들이랑 제가 뷰에 설정한 카테고리 이름들이 달라서 따로 변수를 설정해논거라서요. 그냥 categoryName을 enum으로 만드는 건 어떨까요??

2023-07-24 13:53 UTC, Ji-InPark commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: "술집", foodImage: "soju")
이름이 달라도 상관없지 않나요?? 어차피 switch case 처럼 사용하면 되는거 아닌가요??

2023-07-24 14:01 UTC, choiseoo commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: "술집", foodImage: "soju")
흠 .. 네 다시 한번 고쳐보겠슴다

2023-07-27 04:59 UTC, choiseoo commented on KuleumBridge/Model/TasteAPI.swift
> +    }
1. URL객체로 문자열을 변환한 뒤 값이 없으면 코드가 종료하도록 합니다.
2. 비동기적으로 데이터 가져온 다음 데이터 에러 검사합니다.
3. do-catch문으로 데이터를 [Store]객체로 디코딩합니다. 이후 가져온 데이터를 메인 스레드에서 처리하기 위해 async사용했습니다.
4. task.resume()을 통해 서버로부터 데이터를 가져오는 작업이 시작됩니다~

2023-07-27 05:12 UTC, choiseoo commented on KuleumBridge/Model/TasteAPI.swift
> +    }
https://weekoding.tistory.com/7

링크 참고해서 코드 작성했습니다~!

2023-07-27 05:16 UTC, Ji-InPark requested changes

2023-07-27 05:16 UTC, Ji-InPark commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: Category.술집.title, foodImage: "soju")
categoryName은 이제 필요없습니다!
category에 들어있으니깐 필요한 곳에서 title을 부르게끔 해주세요

2023-07-27 05:36 UTC, choiseoo commented on KuleumBridge/TastePlace/TastePlaceView.swift
> +                    FoodCategoryView(category: .술집, categoryName: Category.술집.title, foodImage: "soju")
넵 반영했습니다

2023-07-27 05:43 UTC, Ji-InPark commented on KuleumBridge/TastePlace/FoodListView.swift
> +    }
이거 title도 아니고 rawValue로 비교해야하나요?? 뭔가 이상한 느낌이네요...

전 `store.category == category` 를 기대했습니다.

2023-07-27 05:47 UTC, choiseoo commented on KuleumBridge/TastePlace/FoodListView.swift
> +    }
store.category는 dataModel을 보면 String값이고, category는 enum이라 비교가 안돼서 .. 
rawValue값 사용했습니다

2023-07-27 05:49 UTC, Ji-InPark commented on KuleumBridge/TastePlace/FoodListView.swift
> +    }
네 그러니깐 store에 category값을 enum으로 받게끔 하는게 좋겠죠?

2023-07-27 05:53 UTC, choiseoo commented on KuleumBridge/TastePlace/FoodListView.swift
> +    }
ㅋㅋ큐ㅠㅠㅠ 네 맞네여 반영했습니다

2023-07-27 05:59 UTC, Ji-InPark approved these changes
enum으로 파싱 잘 되는지 돌려서 확인해봐주세요~ 잘 돌아간다면 머지하시면 됨다

2023-07-27 06:01 UTC, merged