Feature/tabbar
KU-LeumBridge/KULEUM_BRIDGE_IOS pull request #8
Opened 2023-07-09 08:35 UTC by slr-09

## 📚 개요

탭바 기능 구현 완료 
홈, 공지사항 탭 부분만 뷰 연결 필요합니다. 

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

2023-07-09 14:11 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +struct TabbarView: View {
```suggestion
struct TabBarView: View {
```

탭바는 Tab Bar 로 두 단어 입니다~

2023-07-09 14:11 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +    let tabbarText = ["홈", "맛집", "공지사항"]
대체 swift는 왜 상수 선언이 let인걸까요...;;

2023-07-09 14:11 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +            }
```suggestion
                switch selectedIdx {
                case 0:
                    // TODO: 홈 뷰 연결
                    ContentView()
                case 1:
                    TastePlaceView()
                case 2:
                    // TODO: 공지사항 뷰 연결
                    ContentView()
                default:
                    SomethingView()
                }
            }
```
이럴 때는 default로 다른 걸 두고 case에는 모든 index를 넣어두는게 좋습니다.

2023-07-09 14:11 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +                Spacer()
L30에 spacer()는 HStack안에 들어있어야하는 이유가 있나요?

2023-07-09 14:11 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +                }
index 변수 이름을 num이라고 지어서 오히려 좀 헷갈리네요.. 차라리 i나 index가 나을거 같아요

2023-07-10 06:01 UTC, slr-09 commented on KuleumBridge/TabbarView.swift
> +    let tabbarText = ["홈", "맛집", "공지사항"]
글쎼요 ..

2023-07-10 06:06 UTC, slr-09 commented on KuleumBridge/TabbarView.swift
> +                Spacer()
<img width="328" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/101566590/46e84f49-8e6e-4664-977c-0f6bf15b3ad8">
<img width="333" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/101566590/c5b0407b-0b03-4988-adb3-65c499c23968">

왼쪽이 HStack 안에 Spacer() 들어간 경우, 오른쪽이 안들어간 경우입니다. 
중앙이 안맞아서 넣었어요

2023-07-10 07:01 UTC, Ji-InPark requested changes
conflict 나네요 확인하고 해결해주세요~

2023-07-10 07:01 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
파일 이름은 안바꾸셨네요 변경해주세요~

2023-07-10 07:01 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +            }
이 ContentView()나 TastePlaceView() 는 데이터 타입이 어떻게 되나요?
변수로 담아둘 수 있다면 배열 상수로 선언해두고 index로 접근해서 사용하는 것도 좋을 것 같아요

2023-07-10 07:17 UTC, slr-09 commented on KuleumBridge/TabbarView.swift
> +            }
View 타입이라 .. 
이게 가능한지 모르겠네요

2023-07-10 07:17 UTC, slr-09 commented on KuleumBridge/TabbarView.swift
파일 이름도 바꿨는데 코드를 좀 뒤늦게 올려서 다시 한 번 확인 부탁드려요

2023-07-10 07:18 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +            }
한 번 시도해보시고 안되면 말죠 모

2023-07-10 07:19 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
<img width="834" alt="image" src="https://github.com/KU-LeumBridge/KULEUM_BRIDGE_IOS/assets/81283634/2e5f405b-8d20-4227-a3ac-012c2e5f9604">
아마 git에 포함이 안된거 같네요~

2023-07-10 08:03 UTC, slr-09 commented on KuleumBridge/TabbarView.swift
> +            }
될 듯 말 듯 안되네여 나중에 다시 알아보겠습니다

2023-07-10 08:04 UTC, Ji-InPark commented on KuleumBridge/TabbarView.swift
> +            }
안되면 할 필요는 없어요~ 되면 코드가 좀 짧아지는 것뿐이니깐요

2023-07-10 08:16 UTC, Ji-InPark approved these changes
나중에 rebase 알려드릴게요... ㅎㅎ
merge로 conflict 처리하면 잘 꼬일 때가 많아요~

2023-07-10 08:17 UTC, merged